### ISSUE TITLE
Document Eth1 node fallback

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.teku#274] opened 2021-04-23 22:51 UTC
Support for automatic fail-over of eth1-endpoints. Multiple endpoints can be specified with the new --eth1-endpoints CLI option. 

See: https://github.com/ConsenSys/teku/pull/3896

**Comment by alexandratran** [comment] 2021-04-28 18:51
duplicate of #240, fixed by #278

**Closed** 2021-05-18 06:30 UTC
